name: Install pkg

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pkg-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Check package
        run: |
          pip install check-manifest
          check-manifest
          python setup.py check --metadata --strict

      - name: Create package
        run: |
          pip install --upgrade setuptools wheel
          python setup.py sdist

      - name: Verify package
        run: |
          pip install twine==3.2
          twine check dist/*
          python setup.py clean

  pkg-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-14"]  #, windows-2019
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create package
        run: |
          python setup.py sdist

      - name: Install package
        run: |
          pip install dist/* --no-build-isolation
          cd .. & python -c "import kaggle_volclassif ; print(kaggle_volclassif.__version__)"

  install-guardian:
    runs-on: ubuntu-latest
    needs: [pkg-install, pkg-check]
    if: always()
    steps:
      - run: echo "${{ needs.pkg-install.result }}"
      - name: failing...
        if: needs.pkg-install.result == 'failure'
        run: exit 1
      - name: cancelled or skipped...
        if: contains(fromJSON('["cancelled", "skipped"]'), needs.pkg-install.result)
        timeout-minutes: 1
        run: sleep 90
